#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers
from homeLogic import homeLogic

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.4.4'
__CHEETAH_versionTuple__ = (2, 4, 4, 'development', 0)
__CHEETAH_genTime__ = 1329285491.072867
__CHEETAH_genTimestamp__ = 'Tue Feb 14 21:58:11 2012'
__CHEETAH_src__ = 'home.tmpl'
__CHEETAH_srcLastModified__ = 'Tue Feb 14 21:57:39 2012'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class home(homeLogic):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(home, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def renderHTMLPage(self, **KWS):



        ## CHEETAH: main method generated for this template
        trans = KWS.get("trans")
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write(u'''Audio Zones
<hr/>
''')
        for i in VFFSL(SL,"zones",True): # generated from line 5, col 1
            _v = VFFSL(SL,"zoneName",False)(VFFSL(SL,"i",True)) # u'$zoneName($i)' on line 6, col 1
            if _v is not None: write(_filter(_v, rawExpr=u'$zoneName($i)')) # from line 6, col 1.
            write(u''' (Z''')
            _v = VFFSL(SL,"i",True) # u'$i' on line 6, col 17
            if _v is not None: write(_filter(_v, rawExpr=u'$i')) # from line 6, col 17.
            write(u''') is
''')
            if VFFSL(SL,"zoneIsOn",False)(VFFSL(SL,"i",True)): # generated from line 7, col 1
                write(u'''<b>on</b> source ''')
                _v = VFFSL(SL,"source",False)(VFFSL(SL,"i",True)) # u'$source($i)' on line 8, col 18
                if _v is not None: write(_filter(_v, rawExpr=u'$source($i)')) # from line 8, col 18.
                write(u'''
''')
                if VFFSL(SL,"state",False)(VFFSL(SL,"i",True)) != 1: # generated from line 9, col 1
                    write(u'''(''')
                    _v = VFFSL(SL,"stateName",False)(VFFSL(SL,"i",True)) # u'$stateName($i)' on line 10, col 2
                    if _v is not None: write(_filter(_v, rawExpr=u'$stateName($i)')) # from line 10, col 2.
                    write(u''')
''')
            else: # generated from line 12, col 1
                write(u'''off
''')
            write(u'''<br/>
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_home= u'renderHTMLPage'

## END CLASS DEFINITION

if not hasattr(home, '_initCheetahAttributes'):
    templateAPIClass = getattr(home, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(home)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=home()).run()


